Datasets

https://www.kaggle.com/code/dataranch/offensive-stats-eda-model-comparison/input

https://www.kaggle.com/datasets/philiphyde1/nfl-stats-1999-2022/data

Combined Data

In [108]:
import pandas as pd
import kagglehub
import os

# Load data from GitHub
github_url = "https://raw.githubusercontent.com/salomerivas/app-development/refs/heads/main/nfl_offensive_stats.csv"

try:
    offensive_data = pd.read_csv(github_url)
    print("Data loaded successfully from GitHub.")
except Exception as e:
    print("Failed to load data from GitHub:", e)

# Fetch data from Kaggle API
try:
    path = kagglehub.dataset_download("philiphyde1/nfl-stats-1999-2022")  # Downloads the dataset
    print("Data downloaded from Kaggle to:", path)
except Exception as e:
    print(f"Failed to download data from Kaggle: {e}")

# Get the list of files in the downloaded directory dynamically
downloaded_files = os.listdir(path)

# Read each file dynamically (instead of hardcoding paths)
dataframes = []

for file_name in downloaded_files:
    # Skip non-CSV files like .DS_Store
    if not file_name.endswith('.csv'):
        print(f"Skipping non-CSV file: {file_name}")
        continue
    
    file_path = os.path.join(path, file_name)
    try:
        df = pd.read_csv(file_path)
        dataframes.append(df)
        print(f"Data loaded successfully from: {file_path}")
    except Exception as e:
        print(f"Failed to load data from {file_path}: {e}")

# Combine all dataframes from Kaggle dataset into one
if dataframes:
    try:
        kaggle_combined_data = pd.concat(dataframes, ignore_index=True)
        print("All data from Kaggle combined successfully.")
    except Exception as e:
        print(f"Failed to combine Kaggle data: {e}")
else:
    print("No data from Kaggle available to combine.")

# Combine the GitHub data with the Kaggle data (if both are available)
if 'offensive_data' in locals() and 'kaggle_combined_data' in locals():
    try:
        # Combine the data from both sources
        df = pd.concat([offensive_data, kaggle_combined_data], ignore_index=True)
        print("All data combined successfully from both GitHub and Kaggle.")
        print(df.head())  # Display the first few rows of the combined data
    except Exception as e:
        print(f"Failed to combine data from GitHub and Kaggle: {e}")
else:
    print("No data available for combining from one or both sources.")

Data loaded successfully from GitHub.
Data downloaded from Kaggle to: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10
Data loaded successfully from: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/yearly_team_data.csv
Data loaded successfully from: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/weekly_player_data.csv
Skipping non-CSV file: .DS_Store
Data loaded successfully from: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/2024_player_predictions.csv
Data loaded successfully from: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/yearly_player_data.csv
Data loaded successfully from: /Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/weekly_team_data.csv
All data from Kaggle combined successfully.
All data combined successfully from both GitHub and Kaggle.
        game_id player_id position                     player team  pass_cmp  \
0  201909050chi  RodgAa00        QB             Aaron Rodgers  GNB      18.0
1  201909050chi  JoneAa00        RB               Aaron Jones  GNB       0.0
2  201909050chi  ValdMa00        WR  Marquez Valdes-Scantling  GNB       0.0
3  201909050chi  AdamDa01        WR             Davante Adams  GNB       0.0
4  201909050chi  GrahJi00        TE              Jimmy Graham  GNB       0.0

   pass_att  pass_yds  pass_td  pass_int  ...  vacated_receptions  \
0      30.0     203.0      1.0       0.0  ...                 NaN
1       0.0       0.0      0.0       0.0  ...                 NaN
2       0.0       0.0      0.0       0.0  ...                 NaN
3       0.0       0.0      0.0       0.0  ...                 NaN
4       0.0       0.0      0.0       0.0  ...                 NaN

   vacated_receiving_yards  vacated_receiving_air_yards  \
0                      NaN                          NaN
1                      NaN                          NaN
2                      NaN                          NaN
3                      NaN                          NaN
4                      NaN                          NaN

   vacated_yards_after_catch  vacated_reception_td  vacated_rush_attempts  \
0                        NaN                   NaN                    NaN
1                        NaN                   NaN                    NaN
2                        NaN                   NaN                    NaN
3                        NaN                   NaN                    NaN
4                        NaN                   NaN                    NaN

   vacated_rushing_yards  vacated_run_td  vacated_touches  vacated_total_yards
0                    NaN             NaN              NaN                  NaN
1                    NaN             NaN              NaN                  NaN
2                    NaN             NaN              NaN                  NaN
3                    NaN             NaN              NaN                  NaN
4                    NaN             NaN              NaN                  NaN

[5 rows x 301 columns]

GitHub Data Columns

In [109]:
print(offensive_data.columns)

Index(['game_id', 'player_id', 'position ', 'player', 'team', 'pass_cmp',
       'pass_att', 'pass_yds', 'pass_td', 'pass_int', 'pass_sacked',
       'pass_sacked_yds', 'pass_long', 'pass_rating', 'rush_att', 'rush_yds',
       'rush_td', 'rush_long', 'targets', 'rec', 'rec_yds', 'rec_td',
       'rec_long', 'fumbles_lost', 'rush_scrambles', 'designed_rush_att',
       'comb_pass_rush_play', 'comb_pass_play', 'comb_rush_play',
       'Team_abbrev', 'Opponent_abbrev', 'two_point_conv', 'total_ret_td',
       'offensive_fumble_recovery_td', 'pass_yds_bonus', 'rush_yds_bonus',
       'rec_yds_bonus', 'Total_DKP', 'Off_DKP', 'Total_FDP', 'Off_FDP',
       'Total_SDP', 'Off_SDP', 'pass_target_yds', 'pass_poor_throws',
       'pass_blitzed', 'pass_hurried', 'rush_yds_before_contact', 'rush_yac',
       'rush_broken_tackles', 'rec_air_yds', 'rec_yac', 'rec_drops', 'offense',
       'off_pct', 'vis_team', 'home_team', 'vis_score', 'home_score', 'OT',
       'Roof', 'Surface', 'Temperature', 'Humidity', 'Wind_Speed',
       'Vegas_Line', 'Vegas_Favorite', 'Over_Under', 'game_date'],
      dtype='object')

In [113]:
# Check if a specific column exists
column_name = 'pass_td'  # replace with the column you're searching for

if column_name in offensive_data.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'pass_td' column exists in the DataFrame.

In [112]:
# Check if a specific column exists
column_name = 'player'  # replace with the column you're searching for

if column_name in offensive_data.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'player' column exists in the DataFrame.

Kaggle Data Columns

In [71]:
print(kaggle_combined_data.columns)

Index(['team', 'season', 'total_snaps', 'yards_gained', 'touchdown',
       'extra_point_attempt', 'field_goal_attempt', 'total_points',
       'td_points', 'xp_points',
       ...
       'vacated_receptions', 'vacated_receiving_yards',
       'vacated_receiving_air_yards', 'vacated_yards_after_catch',
       'vacated_reception_td', 'vacated_rush_attempts',
       'vacated_rushing_yards', 'vacated_run_td', 'vacated_touches',
       'vacated_total_yards'],
      dtype='object', length=236)

In [92]:
# Check if a specific column exists
column_name = 'player_name'  # replace with the column you're searching for

if column_name in kaggle_combined_data.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'player_name' column exists in the DataFrame.

In [93]:
column_name = 'touchdown'  # replace with the column you're searching for

if column_name in kaggle_combined_data.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'touchdown' column exists in the DataFrame.

In [114]:
df

,game_id,player_id,position,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,vacated_receptions,vacated_receiving_yards,vacated_receiving_air_yards,vacated_yards_after_catch,vacated_reception_td,vacated_rush_attempts,vacated_rushing_yards,vacated_run_td,vacated_touches,vacated_total_yards
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18.0,30.0,203.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83238,NaN,NaN,NaN,NaN,WAS,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83239,NaN,NaN,NaN,NaN,WAS,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83240,NaN,NaN,NaN,NaN,WAS,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83241,NaN,NaN,NaN,NaN,WAS,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83242,NaN,NaN,NaN,NaN,WAS,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Overview of the Dataset

In [115]:
import pandas as pd

# Check the shape
print("Dataset Shape:", df.shape)

print(df.head())

print(df.tail())

# List the column names
print(df.columns)

# Check data types for each column
print(df.dtypes)

Dataset Shape: (83243, 301)
        game_id player_id position                     player team  pass_cmp  \
0  201909050chi  RodgAa00        QB             Aaron Rodgers  GNB      18.0
1  201909050chi  JoneAa00        RB               Aaron Jones  GNB       0.0
2  201909050chi  ValdMa00        WR  Marquez Valdes-Scantling  GNB       0.0
3  201909050chi  AdamDa01        WR             Davante Adams  GNB       0.0
4  201909050chi  GrahJi00        TE              Jimmy Graham  GNB       0.0

   pass_att  pass_yds  pass_td  pass_int  ...  vacated_receptions  \
0      30.0     203.0      1.0       0.0  ...                 NaN
1       0.0       0.0      0.0       0.0  ...                 NaN
2       0.0       0.0      0.0       0.0  ...                 NaN
3       0.0       0.0      0.0       0.0  ...                 NaN
4       0.0       0.0      0.0       0.0  ...                 NaN

   vacated_receiving_yards  vacated_receiving_air_yards  \
0                      NaN                          NaN
1                      NaN                          NaN
2                      NaN                          NaN
3                      NaN                          NaN
4                      NaN                          NaN

   vacated_yards_after_catch  vacated_reception_td  vacated_rush_attempts  \
0                        NaN                   NaN                    NaN
1                        NaN                   NaN                    NaN
2                        NaN                   NaN                    NaN
3                        NaN                   NaN                    NaN
4                        NaN                   NaN                    NaN

   vacated_rushing_yards  vacated_run_td  vacated_touches  vacated_total_yards
0                    NaN             NaN              NaN                  NaN
1                    NaN             NaN              NaN                  NaN
2                    NaN             NaN              NaN                  NaN
3                    NaN             NaN              NaN                  NaN
4                    NaN             NaN              NaN                  NaN

[5 rows x 301 columns]
      game_id player_id position  player team  pass_cmp  pass_att  pass_yds  \
83238     NaN       NaN       NaN    NaN  WAS       NaN       NaN       NaN
83239     NaN       NaN       NaN    NaN  WAS       NaN       NaN       NaN
83240     NaN       NaN       NaN    NaN  WAS       NaN       NaN       NaN
83241     NaN       NaN       NaN    NaN  WAS       NaN       NaN       NaN
83242     NaN       NaN       NaN    NaN  WAS       NaN       NaN       NaN

       pass_td  pass_int  ...  vacated_receptions  vacated_receiving_yards  \
83238      1.0       NaN  ...                 NaN                      NaN
83239      3.0       NaN  ...                 NaN                      NaN
83240      1.0       NaN  ...                 NaN                      NaN
83241      1.0       NaN  ...                 NaN                      NaN
83242      1.0       NaN  ...                 NaN                      NaN

       vacated_receiving_air_yards  vacated_yards_after_catch  \
83238                          NaN                        NaN
83239                          NaN                        NaN
83240                          NaN                        NaN
83241                          NaN                        NaN
83242                          NaN                        NaN

       vacated_reception_td  vacated_rush_attempts  vacated_rushing_yards  \
83238                   NaN                    NaN                    NaN
83239                   NaN                    NaN                    NaN
83240                   NaN                    NaN                    NaN
83241                   NaN                    NaN                    NaN
83242                   NaN                    NaN                    NaN

       vacated_run_td  vacated_touches  vacated_total_yards
83238             NaN              NaN                  NaN
83239             NaN              NaN                  NaN
83240             NaN              NaN                  NaN
83241             NaN              NaN                  NaN
83242             NaN              NaN                  NaN

[5 rows x 301 columns]
Index(['game_id', 'player_id', 'position ', 'player', 'team', 'pass_cmp',
       'pass_att', 'pass_yds', 'pass_td', 'pass_int',
       ...
       'vacated_receptions', 'vacated_receiving_yards',
       'vacated_receiving_air_yards', 'vacated_yards_after_catch',
       'vacated_reception_td', 'vacated_rush_attempts',
       'vacated_rushing_yards', 'vacated_run_td', 'vacated_touches',
       'vacated_total_yards'],
      dtype='object', length=301)
game_id                   object
player_id                 object
position                  object
player                    object
team                      object
                          ...
vacated_rush_attempts    float64
vacated_rushing_yards    float64
vacated_run_td           float64
vacated_touches          float64
vacated_total_yards      float64
Length: 301, dtype: object

Statistics

In [116]:
# Summary statistics for numerical columns
print(df.describe())

# Summary statistics for categorical columns
print(df.describe(include=['object']))

/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/numpy/_core/_methods.py:53: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
/Users/salomerivas/Desktop/COMILLAS/APP DEVELOPMENT FOLDER/Project/venv/lib/python3.12/site-packages/numpy/_core/_methods.py:53: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

           pass_cmp      pass_att      pass_yds       pass_td      pass_int  \
count  19973.000000  19973.000000  19973.000000  83243.000000  19973.000000
mean       1.844240      2.860011     20.565513      0.519539      0.064988
std        6.294815      9.659786     70.841227      2.649633      0.336662
min        0.000000      0.000000     -2.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max       47.000000     68.000000    525.000000     57.000000      5.000000

        pass_sacked  pass_sacked_yds     pass_long   pass_rating  \
count  19973.000000     19973.000000  19973.000000  19973.000000
mean       0.192059         1.299354      3.401742      9.026606
std        0.789580         5.613713     11.543382     28.645285
min        0.000000         0.000000     -2.000000      0.000000
25%        0.000000         0.000000      0.000000      0.000000
50%        0.000000         0.000000      0.000000      0.000000
75%        0.000000         0.000000      0.000000      0.000000
max        9.000000        79.000000     93.000000    158.300000

           rush_att  ...  vacated_receptions  vacated_receiving_yards  \
count  19973.000000  ...         5304.000000              5304.000000
mean       2.179392  ...           92.792798              1012.265837
std        4.739141  ...           57.576352               654.825181
min        0.000000  ...            0.000000                 0.000000
25%        0.000000  ...           52.000000               574.000000
50%        0.000000  ...           85.000000               955.000000
75%        2.000000  ...          134.000000              1444.000000
max       35.000000  ...          261.000000              3064.000000

       vacated_receiving_air_yards  vacated_yards_after_catch  \
count                  5304.000000                5304.000000
mean                   1209.688537                 450.870852
std                     863.505376                 295.008928
min                       0.000000                   0.000000
25%                     587.000000                 235.000000
50%                    1075.000000                 424.000000
75%                    1689.000000                 646.000000
max                    3561.000000                1273.000000

       vacated_reception_td  vacated_rush_attempts  vacated_rushing_yards  \
count           5304.000000            5304.000000            5304.000000
mean               6.269419             117.018854             479.463801
std                4.795537             108.094482             442.960916
min                0.000000               0.000000               0.000000
25%                3.000000              22.000000              94.000000
50%                6.000000              87.000000             352.000000
75%                9.000000             204.000000             781.000000
max               23.000000             411.000000            1979.000000

       vacated_run_td  vacated_touches  vacated_total_yards
count     5304.000000      5304.000000          5304.000000
mean         3.359540       355.601433          2347.222662
std          3.555581       293.167502          1810.456718
min          0.000000         0.000000             0.000000
25%          0.000000       123.000000          1017.000000
50%          2.000000       283.000000          1961.000000
75%          5.000000       504.500000          3264.000000
max         19.000000      1215.000000          8121.000000

[8 rows x 281 columns]
             game_id   player_id position              player   team  \
count          19973       76675     19973              19973  83243
unique           820        2609        28               1019     40
top     202010110sfo  00-0029263        WR  Demarcus Robinson    BAL
freq              29         200      7904                 57   2824

       Team_abbrev Opponent_abbrev vis_team home_team     OT      Roof  \
count        19973           19973    19973     19973  19973     19973
unique          32              32       32        32      2         4
top            KAN             KAN      TAM       KAN  False  outdoors
freq           743             693      709       823  18911     13831

       Surface Vegas_Favorite game_date   record     player_name position  \
count    19973          19927     19973      384           56702    56702
unique       8             33       174       42            1584        4
top      grass            KAN  1/3/2021  \t7-9-0  Russell Wilson       WR
freq      9002           1318       391       37             200    22734

       game_type opponent   college
count      56526    50863     56698
unique         1       32       276
top          REG      NYG  Oklahoma
freq       56526     1713      1521

In [117]:
# Check if a specific column exists
column_name1 = 'player_name'  # replace with the column you're searching for
column_name2 = 'player'  # replace with the column you're searching for

if column_name1 in df.columns:
    print(f"'{column_name1}' column exists in the DataFrame.")
else:
    print(f"'{column_name1}' column does not exist in the DataFrame.")

if column_name2 in df.columns:
    print(f"'{column_name2}' column exists in the DataFrame.")
else:
    print(f"'{column_name2}' column does not exist in the DataFrame.")

'player_name' column exists in the DataFrame.
'player' column exists in the DataFrame.

In [118]:
# Check if a specific column exists
column_name3 = 'pass_td'  # replace with the column you're searching for
column_name4 = 'touchdown'  # replace with the column you're searching for

if column_name3 in df.columns:
    print(f"'{column_name3}' column exists in the DataFrame.")
else:
    print(f"'{column_name3}' column does not exist in the DataFrame.")

if column_name4 in df.columns:
    print(f"'{column_name4}' column exists in the DataFrame.")
else:
    print(f"'{column_name4}' column does not exist in the DataFrame.")

'pass_td' column exists in the DataFrame.
'touchdown' column exists in the DataFrame.

Combine the data for players into just one player column and just one row of data per player

In [119]:
# Combine the columns into a new 'players' column
df['players'] = pd.concat([df['player_name'], df['player']], axis=0).reset_index(drop=True)

# Fill missing values in 'players' with the values from 'player'
df['players'] = df['players'].fillna(df['player'])

# Optionally, drop the old columns if no longer needed
df = df.drop(columns=['player_name', 'player'])

print(df)

            game_id player_id position  team  pass_cmp  pass_att  pass_yds  \
0      201909050chi  RodgAa00        QB  GNB      18.0      30.0     203.0
1      201909050chi  JoneAa00        RB  GNB       0.0       0.0       0.0
2      201909050chi  ValdMa00        WR  GNB       0.0       0.0       0.0
3      201909050chi  AdamDa01        WR  GNB       0.0       0.0       0.0
4      201909050chi  GrahJi00        TE  GNB       0.0       0.0       0.0
...             ...       ...       ...  ...       ...       ...       ...
83238           NaN       NaN       NaN  WAS       NaN       NaN       NaN
83239           NaN       NaN       NaN  WAS       NaN       NaN       NaN
83240           NaN       NaN       NaN  WAS       NaN       NaN       NaN
83241           NaN       NaN       NaN  WAS       NaN       NaN       NaN
83242           NaN       NaN       NaN  WAS       NaN       NaN       NaN

       pass_td  pass_int  pass_sacked  ...  vacated_receiving_yards  \
0          1.0       0.0          5.0  ...                      NaN
1          0.0       0.0          0.0  ...                      NaN
2          0.0       0.0          0.0  ...                      NaN
3          0.0       0.0          0.0  ...                      NaN
4          0.0       0.0          0.0  ...                      NaN
...        ...       ...          ...  ...                      ...
83238      1.0       NaN          NaN  ...                      NaN
83239      3.0       NaN          NaN  ...                      NaN
83240      1.0       NaN          NaN  ...                      NaN
83241      1.0       NaN          NaN  ...                      NaN
83242      1.0       NaN          NaN  ...                      NaN

       vacated_receiving_air_yards  vacated_yards_after_catch  \
0                              NaN                        NaN
1                              NaN                        NaN
2                              NaN                        NaN
3                              NaN                        NaN
4                              NaN                        NaN
...                            ...                        ...
83238                          NaN                        NaN
83239                          NaN                        NaN
83240                          NaN                        NaN
83241                          NaN                        NaN
83242                          NaN                        NaN

       vacated_reception_td  vacated_rush_attempts  vacated_rushing_yards  \
0                       NaN                    NaN                    NaN
1                       NaN                    NaN                    NaN
2                       NaN                    NaN                    NaN
3                       NaN                    NaN                    NaN
4                       NaN                    NaN                    NaN
...                     ...                    ...                    ...
83238                   NaN                    NaN                    NaN
83239                   NaN                    NaN                    NaN
83240                   NaN                    NaN                    NaN
83241                   NaN                    NaN                    NaN
83242                   NaN                    NaN                    NaN

       vacated_run_td  vacated_touches  vacated_total_yards  \
0                 NaN              NaN                  NaN
1                 NaN              NaN                  NaN
2                 NaN              NaN                  NaN
3                 NaN              NaN                  NaN
4                 NaN              NaN                  NaN
...               ...              ...                  ...
83238             NaN              NaN                  NaN
83239             NaN              NaN                  NaN
83240             NaN              NaN                  NaN
83241             NaN              NaN                  NaN
83242             NaN              NaN                  NaN

                        players
0                 Aaron Rodgers
1                   Aaron Jones
2      Marquez Valdes-Scantling
3                 Davante Adams
4                  Jimmy Graham
...                         ...
83238                       NaN
83239                       NaN
83240                       NaN
83241                       NaN
83242                       NaN

[83243 rows x 300 columns]

/var/folders/z5/9p6mflxn16bfxvds_w7ffs5m0000gn/T/ipykernel_81628/284913150.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['players'] = pd.concat([df['player_name'], df['player']], axis=0).reset_index(drop=True)

In [121]:
# Check if a specific column exists
column_name = 'players'  # replace with the column you're searching for

if column_name in df.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'players' column exists in the DataFrame.

Check for missing values

In [123]:
if 'players' in df.columns:
    print("The 'players' column exists!")
else:
    print("The 'players' column does not exist.")
print(df.players)

The 'players' column exists!
0                   Aaron Rodgers
1                     Aaron Jones
2        Marquez Valdes-Scantling
3                   Davante Adams
4                    Jimmy Graham
                   ...
83238                         NaN
83239                         NaN
83240                         NaN
83241                         NaN
83242                         NaN
Name: players, Length: 83243, dtype: object

In [125]:
# Drop rows with NaN values in 'players' column, modifying the original dataframe
df.dropna(subset=['players'], inplace=True)

# Print the first few rows of the cleaned dataframe
print(df.players)

0                   Aaron Rodgers
1                     Aaron Jones
2        Marquez Valdes-Scantling
3                   Davante Adams
4                    Jimmy Graham
                   ...
77054                   Zay Jones
77055                   Zay Jones
77056                   Zay Jones
77057              Zonovan Knight
77058              Zonovan Knight
Name: players, Length: 76675, dtype: object

In [126]:
df['players'] = df['players'].str.strip().str.lower()
print(df)

            game_id   player_id position  team  pass_cmp  pass_att  pass_yds  \
0      201909050chi    RodgAa00        QB  GNB      18.0      30.0     203.0
1      201909050chi    JoneAa00        RB  GNB       0.0       0.0       0.0
2      201909050chi    ValdMa00        WR  GNB       0.0       0.0       0.0
3      201909050chi    AdamDa01        WR  GNB       0.0       0.0       0.0
4      201909050chi    GrahJi00        TE  GNB       0.0       0.0       0.0
...             ...         ...       ...  ...       ...       ...       ...
77054           NaN  00-0033891       NaN   LV       NaN       NaN       NaN
77055           NaN  00-0033891       NaN  JAX       NaN       NaN       NaN
77056           NaN  00-0033891       NaN  JAX       NaN       NaN       NaN
77057           NaN  00-0037157       NaN  NYJ       NaN       NaN       NaN
77058           NaN  00-0037157       NaN  DET       NaN       NaN       NaN

       pass_td  pass_int  pass_sacked  ...  vacated_receiving_yards  \
0          1.0       0.0          5.0  ...                      NaN
1          0.0       0.0          0.0  ...                      NaN
2          0.0       0.0          0.0  ...                      NaN
3          0.0       0.0          0.0  ...                      NaN
4          0.0       0.0          0.0  ...                      NaN
...        ...       ...          ...  ...                      ...
77054      0.0       NaN          NaN  ...                      0.0
77055      0.0       NaN          NaN  ...                   1988.0
77056      0.0       NaN          NaN  ...                   2164.0
77057      0.0       NaN          NaN  ...                   1044.0
77058      0.0       NaN          NaN  ...                    979.0

       vacated_receiving_air_yards  vacated_yards_after_catch  \
0                              NaN                        NaN
1                              NaN                        NaN
2                              NaN                        NaN
3                              NaN                        NaN
4                              NaN                        NaN
...                            ...                        ...
77054                          0.0                        0.0
77055                       2705.0                      688.0
77056                       2396.0                     1189.0
77057                       1525.0                      433.0
77058                       1168.0                      407.0

       vacated_reception_td  vacated_rush_attempts  vacated_rushing_yards  \
0                       NaN                    NaN                    NaN
1                       NaN                    NaN                    NaN
2                       NaN                    NaN                    NaN
3                       NaN                    NaN                    NaN
4                       NaN                    NaN                    NaN
...                     ...                    ...                    ...
77054                   0.0                    0.0                    0.0
77055                  12.0                   44.0                  213.0
77056                   7.0                  310.0                 1302.0
77057                   7.0                  248.0                 1052.0
77058                   5.0                   35.0                  212.0

       vacated_run_td  vacated_touches  vacated_total_yards  \
0                 NaN              NaN                  NaN
1                 NaN              NaN                  NaN
2                 NaN              NaN                  NaN
3                 NaN              NaN                  NaN
4                 NaN              NaN                  NaN
...               ...              ...                  ...
77054             0.0              0.0                  0.0
77055             2.0            895.0               5908.0
77056            10.0            533.0               3466.0
77057             6.0            747.0               4072.0
77058             3.0            232.0               1713.0

                        players
0                 aaron rodgers
1                   aaron jones
2      marquez valdes-scantling
3                 davante adams
4                  jimmy graham
...                         ...
77054                 zay jones
77055                 zay jones
77056                 zay jones
77057            zonovan knight
77058            zonovan knight

[76675 rows x 300 columns]

In [127]:
# Check if a specific column exists
column_name = 'players'  # replace with the column you're searching for

if column_name in df.columns:
    print(f"'{column_name}' column exists in the DataFrame.")
else:
    print(f"'{column_name}' column does not exist in the DataFrame.")

'players' column exists in the DataFrame.

In [ ]:
# Define a custom aggregation function
aggregation_dict = {}

# For numeric columns, apply 'sum'
numeric_cols = df.select_dtypes(include=['number']).columns
for col in numeric_cols:
    aggregation_dict[col] = 'sum'

# For non-numeric columns, apply 'first'
non_numeric_cols = df.select_dtypes(exclude=['number']).columns
for col in non_numeric_cols:
    aggregation_dict[col] = 'first'  # You can choose other methods like 'last' or 'mode'

# Perform the aggregation without resetting the index (player remains the index)
df_player_aggregated = df.groupby('player').agg(aggregation_dict)

# Print the first few rows of the aggregated data
print(df_player_aggregated.head())

               season  week  pass_attempts  complete_pass  incomplete_pass  \
player
a.j. brown        0.0   0.0            0.0            0.0              0.0
a.j. green        0.0   0.0            0.0            0.0              0.0
a.j. mccarron     0.0   0.0            0.0            0.0              0.0
aaron brewer      0.0   0.0            0.0            0.0              0.0
aaron fuller      0.0   0.0            0.0            0.0              0.0

               passing_yards  passing_air_yards  touchdown  interception  \
player
a.j. brown               0.0                0.0        0.0           0.0
a.j. green               0.0                0.0        0.0           0.0
a.j. mccarron            0.0                0.0        0.0           0.0
aaron brewer             0.0                0.0        0.0           0.0
aaron fuller             0.0                0.0        0.0           0.0

               pass_fumble_lost  ...         player  Team_abbrev  \
player                           ...
a.j. brown                  0.0  ...     a.j. brown          TEN
a.j. green                  0.0  ...     a.j. green          CIN
a.j. mccarron               0.0  ...  a.j. mccarron          HOU
aaron brewer                0.0  ...   aaron brewer          TEN
aaron fuller                0.0  ...   aaron fuller          SEA

               Opponent_abbrev  vis_team  home_team     OT  \
player
a.j. brown                 CLE       TEN        CLE  False
a.j. green                 LAC       LAC        CIN  False
a.j. mccarron              BAL       HOU        BAL  False
aaron brewer               CLE       CLE        TEN  False
aaron fuller               ARI       SEA        ARI  False

                                  Roof  Surface  Vegas_Favorite   game_date
player
a.j. brown                    outdoors    grass             CLE    9/8/2019
a.j. green                    outdoors    grass             LAC   9/13/2020
a.j. mccarron                 outdoors    grass             BAL  11/17/2019
aaron brewer                  outdoors    grass             TEN   12/6/2020
aaron fuller   retractable roof (open)   grass              ARI    1/9/2022

[5 rows x 131 columns]

In [85]:
# Search for a player (e.g., 'Aaron Rodgers') in the 'player' column
player_name = "Justin Jefferson"
search_results = df_player_aggregated[df_player_aggregated['player'].str.contains(player_name, case=False, na=False)]

# Print the rows that contain the player's name
print(search_results)

                  season  week  pass_attempts  complete_pass  incomplete_pass  \
player
justin jefferson     0.0   0.0            0.0            0.0              0.0

                  passing_yards  passing_air_yards  touchdown  interception  \
player
justin jefferson            0.0                0.0        0.0           0.0

                  pass_fumble_lost  ...            player  Team_abbrev  \
player                              ...
justin jefferson               0.0  ...  justin jefferson          MIN

                  Opponent_abbrev  vis_team  home_team     OT  Roof  \
player
justin jefferson              GNB       GNB        MIN  False  dome

                    Surface  Vegas_Favorite  game_date
player
justin jefferson  sportturf             MIN  9/13/2020

[1 rows x 131 columns]

In [86]:
# Ensure the 'player' column exists in combined_df for filtering
if 'player' in df_player_aggregated.columns:
    # Filter rows where 'player' is 'Justin Jefferson'
    justin_jefferson_data = df_player_aggregated[df_player_aggregated['player'] == 'Justin Jefferson']
    
    # Display the 'touchdown' and 'pass_td' columns for Justin Jefferson
    justin_jefferson_touchdowns = justin_jefferson_data[['touchdown', 'pass_td']]
    print(justin_jefferson_touchdowns)
else:
    print("The 'player' column is not present in the combined dataset.")

KeyError: "['pass_td'] not in index"

Combine the data of touchdowns from both datasets

In [ ]:
# Load datasets (update paths as necessary)
df1 = pd.read_csv('/Users/salomerivas/.cache/kagglehub/datasets/philiphyde1/nfl-stats-1999-2022/versions/10/weekly_player_data.csv')
df2 = pd.read_csv('https://raw.githubusercontent.com/salomerivas/app-development/refs/heads/main/nfl_offensive_stats.csv')

# Function to rename touchdown-related columns to a consistent 'touchdown' column
def rename_touchdown_column(df):
    # Rename touchdown-related columns to 'touchdown'
    if 'pass_td' in df.columns:
        df = df.rename(columns={'pass_td': 'touchdown'})
    elif 'touchdown' in df.columns:
        # Already has 'touchdown', no renaming needed
        pass
    else:
        print("Warning: No touchdown-related column found in this dataframe.")
    
    return df

# Apply the function to both datasets
df1 = rename_touchdown_column(df1)
df2 = rename_touchdown_column(df2)

# Combine both datasets into one (concatenate them vertically)
touchdown_combined_df = pd.concat([df1, df2], ignore_index=True)

# Now, you have a single dataset with all touchdown data in the 'touchdown' column
print(touchdown_combined_df.head())

  team   player_id player_name position  season  week game_type  \
0  TEN  00-0035676  A.J. Brown       WR  2019.0   1.0       REG
1  TEN  00-0035676  A.J. Brown       WR  2019.0   2.0       REG
2  TEN  00-0035676  A.J. Brown       WR  2019.0   3.0       REG
3  TEN  00-0035676  A.J. Brown       WR  2019.0   4.0       REG
4  TEN  00-0035676  A.J. Brown       WR  2019.0   5.0       REG

   pass_attempts  complete_pass  incomplete_pass  ...   OT  Roof  Surface  \
0            0.0            0.0              0.0  ...  NaN   NaN      NaN
1            0.0            0.0              0.0  ...  NaN   NaN      NaN
2            0.0            0.0              0.0  ...  NaN   NaN      NaN
3            0.0            0.0              0.0  ...  NaN   NaN      NaN
4            0.0            0.0              0.0  ...  NaN   NaN      NaN

   Temperature  Humidity  Wind_Speed  Vegas_Line  Vegas_Favorite  Over_Under  \
0          NaN       NaN         NaN         NaN             NaN         NaN
1          NaN       NaN         NaN         NaN             NaN         NaN
2          NaN       NaN         NaN         NaN             NaN         NaN
3          NaN       NaN         NaN         NaN             NaN         NaN
4          NaN       NaN         NaN         NaN             NaN         NaN

   game_date
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

[5 rows x 131 columns]

In [ ]:
# Find the index of the player with the highest number of touchdowns
top_touchdown_index = df_player_aggregated['touchdown'].idxmax()

# Get the player with the highest number of touchdowns using that index
top_touchdown_player = df_player_aggregated.loc[top_touchdown_index]

# Print the player's name and the number of touchdowns
print("Player with the highest touchdowns:")
print(top_touchdown_player[['player', 'touchdown']])

KeyError: 'touchdown'

In [ ]:
# Converting to datetime.date values
df_player_aggregated['birthDate'] = pd.to_datetime(df_player_aggregated['birthDate']).dt.date

# Extracting the year
df_player_aggregated['birthYear'] = pd.to_datetime(df_player_aggregated['birthDate']).dt.year

# Looking at the first five rows
df_player_aggregated.head()

,pass_cmp,pass_att,pass_yds,pass_td,pass_int,pass_sacked,pass_sacked_yds,pass_long,pass_rating,rush_att,...,displayName,playDirection,route,birthDate,collegeName,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr,birthYear
player,,,,,,,,,,,,,,,,,,,,,
a.j. brown,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,79.2,6.0,...,None,None,None,NaT,None,None,None,None,None,NaN
a.j. green,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,None,None,None,NaT,None,None,None,None,None,NaN
a.j. mccarron,22.0,38.0,245.0,0.0,1.0,6.0,55.0,41.0,223.5,5.0,...,None,None,None,NaT,None,None,None,None,None,NaN
aaron brewer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,None,None,None,NaT,None,None,None,None,None,NaN
aaron fuller,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,None,None,None,NaT,None,None,None,None,None,NaN

In [ ]:
if 'player' in df_player_aggregated.columns and 'birthDate' in df_player_aggregated.columns: 
    desmond_trufant = df_player_aggregated[df_player_aggregated['player'].str.contains('Saquon Barkley', case=False, na=False)]

    # Check if any records were found
    if not desmond_trufant.empty:
        print("Saquon Barkley birth date(s):")
        print(desmond_trufant[['player', 'birthDate']])
    else:
            print("Saquon Barkley not found in the dataset.")
else:
    print("The dataset does not have the required columns: 'player' and 'birthDate'.")

Saquon Barkley birth date(s):
                        player birthDate
player
saquon barkley  saquon barkley       NaT

In [ ]:
df_player_aggregated.shape

(1019, 350)